baseURL = "https://alessandrogiovannacci.github.io/personalwebpage/"
publishDir = "docs"
languageCode = "en-us"
theme = "sada"
disableKinds = ["taxonomy", "taxonomyTerm"]

###################################################################################

[params]
    title = "Alessandro's web page"
    author = "Alessandro Giovannacci"
    description = "About me"
    copyright = "© 2022, Alessandro Giovannacci"
    copyright_link = ""

    # Profile section
    [params.profile]
        name = "Alessandro Giovannacci"
        photo = "ale.jpg"

###################################################################################

    # Section for links to social websites

    [params.social]

        title = "Links"

        #[[params.social.list]]
        #class = "fab"
        #icon = "fa-linkedin-in"
        #url = "#"
        #title = "LinkedIn"

        [[params.social.list]]
        class = "fab"
        icon = "fa-github"
        url = "https://github.com/alessandrogiovannacci"
        title = "GitHub"

		#[[params.social.list]]
        #class = "ai"
        #icon = "ai-google-scholar"
        #url = "#"
        #title = "Google Scholar"

###################################################################################

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Master of Science in Computer Science"
        college = "Università degli studi dell'Insubria"
        dates = "october 2018 - december 2020"
        thesis_title = "Design and development of applications related to system engineering activities of astronomical instrumentation with SysML"
        thesis_link = "thesis_728707.pdf"

        [[params.education.list]]
        degree = "Bachelor of Science in Computer Science"
        college = "Università degli studi dell'Insubria"
        dates = "november 2015 - september 2018"
        thesis_title = "Alberi e strutture ordinate: una implementazione in Java"
        thesis_link = "Tesi_Giovannacci_Alessandro_F004.pdf"

        

###################################################################################

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "Italian"
        level = "First language"
				
        [[params.language.list]]
        language = "English"
        level = "B2 level of CEFR scale"

###################################################################################

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Travelling"
		
		[[params.hobbies.list]]
        interest = "Logic games"

        [[params.hobbies.list]]
        interest = "Running, swimming, functional training"

        [[params.hobbies.list]]
        interest = "Kitesurfing"

        [[params.hobbies.list]]
        interest = "Reading"

        [[params.hobbies.list]]
        interest = "Video games"

        [[params.hobbies.list]]
        interest = "Enigmatography"

###################################################################################

    [params.aboutme]
        description = "My course of study at Università degli studi dell'Insubria provided a specialization in the `software engineering`'s field, as well as in `data management, analysis and security`. What can I say about me with few words? I am curious, I want to understand how things work, and I always want to learn new things. At work, others describe me as very precise and organized. I have many interests, I obviously cannot fail to mention `programming` (even in my spare time). I am also very interested about what concerns the universe: this is due to various science documentaries I watched over the years, stimulating my curiosity about what's outside of the Earth. Last but not least, I am a passionate gamer from the age of 6."


###################################################################################

    # Experiences section
    [params.experiences]
        icon = "fa-briefcase"
        title = "Last experiences"

        [[params.jobs.list]]
        position = "Software engineer"
        dates = "2022 - presen"
        link = "https://www.arca24.com/it/"
        company = "Arca24"
        details = "Backend software development for employment agencies."

        [[params.jobs.list]]
        position = "Software engineer"
        dates = "2021 - 2022"
		link = "https://it.linkedin.com/company/iriscube-reply"
        company = "Iriscube Reply"
        details = "Backend software development for banks."

        [[params.jobs.list]]
        position = "Trainee"
        dates = "2019 - 2020"
		link = "http://www.inaf.it/it"
        company = "National Institute for Astrophysics (INAF)"
        details = "Curricular internship at Università degli studi dell'Insubria (internal training)."

        [[params.jobs.list]]
        position = "Employee"
        dates = "2015 - 2021"
		link = "#"
        company = "Varese professionisti"
        details = "Accounting management, Information Technology manager, Programmer (ad hoc software for internal use)."

        [[params.jobs.list]]
        position = "Employee"
        dates = "2015"
		link = "#"
        company = "GPA"
        details = "Developing software for avionic simulators (Qt framework)."

        [[params.jobs.list]]
        position = "For a complete overview, you can have a look at my cv."
        dates = ""
        link = "curriculum_vitae_AG.pdf"
        company = "Curriculum vitae"

###################################################################################

    # Projects section
    [params.projects]
        icon = "fa-project-diagram"
        title = "Academic projects"

        [[params.projects.list]]
        title = "Java plugin for Cameo Systems Modeler"
        url = "#"
        description = "INAF (National Institute for Astrophysics) required a software system that simplifies the generation of a specific file in Cameo Systems Modeler context: the report. The first task is the creation of a Velocity template, which is a specific file that contains a VTL script. Once the template file has been created, the configuration of the Report Wizard is fundamental, because the entire report generation process can be customized, specifying the scope from which the diagram extrapolation must begin, as well as setting the Report data, a collection of report which can be included in the generated report, and output options. The last step is the implementation of a Cameo Systems Modeler plugin, using the Java language. CSM is mainly written in Java, and developers made available a specific Application Programming Interface (API) through which extensions can be written and included in the software."

        [[params.projects.list]]
        title = "Watchneighbors"
        url = "#"
        description = "Stand-alone java application that monitors the neighborhood. This application lets the user report abnormal events, visualize them and take them in charge. Users can visualize reports list of their neighborhood. Data retention is carried out through csv files."
		
		[[params.projects.list]]
        title = "seatIn"
        url = "#"
        description = "Client-server application developed with Java technology. It is the acronym of simple e-learning at Insubria; the software recreates a typical e-learning platform, where professors, students and administrators login with their username and password, share files, update their profiles, visualize information about courses provided by the university. Used technologies: RMI for client/server communication, PostgreSQL for storing and managing data, JDBC for interfacing Java app with DBMS."

        [[params.projects.list]]
        title = "Data analysis with R"
        url = "#"
        description = "Data analysis with R language using RStudio IDE. Dataset ant-1.7.csv, containing 745 objects (Java classes) of 24 variables. The purpose of the project is to analyze the defectiveness of the software, correlating dependent variable bugs with other independent variables (depth of inheritance tree, number of children, lines of code), establishing the correlation between the first variable and the others. Binary logistic regression analysis has been used."

        [[params.projects.list]]
        title = "GMaker"
        url = "#"
        description = "Software written in Java; it lets the user create graphs by defining ordered sets. GMaker requires Graphviz, a graph generator application, that allows to generate graphs that are initially represented as files with dot extension. GMaker generates a file with dot extension, and this file is the input for the program that render it, and generates a graph drawing, or equivalently, the Hasse diagram; at this point, GMaker takes care of showing to the user the generated graph. Various graphs can be generated, as they represent different algebraic structures: partition of a set, down-sets of a poset, disjoined down-sets of a poset, join-irreducible elements set of a poset."

###################################################################################

    # Skills section
    [params.skills]
        icon = "fa-cogs"
        title = "Skills"

        [[params.skills.list]]

        skill = "OOP"

        skillrating = 100


        [[params.skills.list]]

        skill = "Java"

        skillrating = 90


        [[params.skills.list]]

        skill = "PHP"

        skillrating = 70


        [[params.skills.list]]

        skill = "JavaFX"

        skillrating = 80


        [[params.skills.list]]

        skill = "Apache Velocity"

        skillrating = 80


        [[params.skills.list]]

        skill = "SQL"

        skillrating = 90


        [[params.skills.list]]

        skill = "MySQL"

        skillrating = 70

		
        [[params.skills.list]]

        skill = "PostgreSQL"

        skillrating = 80


        [[params.skills.list]]

        skill = "MongoDB"

        skillrating = 50

        [[params.skills.list]]

        skill = "Oracle"

        skillrating = 70


        [[params.skills.list]]

        skill = "SQLite"

        skillrating = 70


        [[params.skills.list]]

        skill = "Batch scripting"

        skillrating = 70


        [[params.skills.list]]

        skill = "C"

        skillrating = 60


        [[params.skills.list]]

        skill = "Git"

        skillrating = 50


        [[params.skills.list]]

        skill = "C++"

        skillrating = 40


        [[params.skills.list]]

        skill = "UML"

        skillrating = 50


        [[params.skills.list]]

        skill = "Apache Ant"

        skillrating = 50


        [[params.skills.list]]

        skill = "Scala"

        skillrating = 30


        [[params.skills.list]]

        skill = "Power BI"

        skillrating = 60


        [[params.skills.list]]

        skill = "R"

        skillrating = 30